In [6]:
from sklearn.datasets import load_boston
import matplotlib.pyplot as plt
import numpy as np

In [7]:
boston = load_boston()
boston["data"]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [8]:
x_data = boston.data
y_data = boston.target.reshape(boston.target.size,1)

In [9]:
y_data.shape

(506, 1)

In [10]:
from sklearn import preprocessing

minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,5)).fit(x_data)
# standard_scale = preprocessing.StandardScaler().fit(x_data)
x_scaled_data = minmax_scale.transform(x_data)

x_scaled_data[:3]

array([[0.00000000e+00, 9.00000000e-01, 3.39076246e-01, 0.00000000e+00,
        1.57407407e+00, 2.88752635e+00, 3.20803296e+00, 1.34601570e+00,
        0.00000000e+00, 1.04007634e+00, 1.43617021e+00, 5.00000000e+00,
        4.48399558e-01],
       [1.17961270e-03, 0.00000000e+00, 1.21151026e+00, 0.00000000e+00,
        8.64197531e-01, 2.73998850e+00, 3.91349125e+00, 1.74480990e+00,
        2.17391304e-01, 5.24809160e-01, 2.76595745e+00, 5.00000000e+00,
        1.02235099e+00],
       [1.17848872e-03, 0.00000000e+00, 1.21151026e+00, 0.00000000e+00,
        8.64197531e-01, 3.47192949e+00, 2.99691040e+00, 1.74480990e+00,
        2.17391304e-01, 5.24809160e-01, 2.76595745e+00, 4.94868627e+00,
        3.17328918e-01]])

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x_scaled_data, y_data, test_size=0.33)

In [13]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((339, 13), (167, 13), (339, 1), (167, 1))

In [14]:
from sklearn import  linear_model

regr = linear_model.LinearRegression(fit_intercept=True, 
                                     normalize=False, 
                                     copy_X=True, 
                                     n_jobs=8)
regr.fit(X_train, y_train)
regr

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=8, normalize=False)

In [16]:
regr.coef_ , regr.intercept_ # coef : 계수 w1,w2,...,wn   intercept : y절편(bias) w0

(array([[-2.16347952,  0.94781542,  0.11399607,  0.62197273, -2.13166919,
          3.3844517 ,  0.05395   , -3.64961268,  1.63305814, -1.32952219,
         -1.77127494,  0.65774785, -4.0892909 ]]), array([29.59088511]))

In [17]:
print('Coefficients: ', regr.coef_)
print('intercept: ', regr.intercept_)

Coefficients:  [[-2.16347952  0.94781542  0.11399607  0.62197273 -2.13166919  3.3844517
   0.05395    -3.64961268  1.63305814 -1.32952219 -1.77127494  0.65774785
  -4.0892909 ]]
intercept:  [29.59088511]


In [27]:
regr.predict(x_data[:5])

array([[-121.71278855],
       [ -89.12471774],
       [ -69.28002059],
       [ -43.00939398],
       [ -50.41160475]])

In [23]:
x_data[:5].dot(regr.coef_.T) + regr.intercept_ # = y추정값(y햇), 위에랑 값은결과

array([[-121.71278855],
       [ -89.12471774],
       [ -69.28002059],
       [ -43.00939398],
       [ -50.41160475]])

In [29]:
y_true = y_test
y_hat = regr.predict(X_test)

np.sqrt(((y_true-y_hat)**2).sum()/len(y_true)) # RMSE

4.908148431451747

In [24]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [31]:
np.sqrt(mean_squared_error(y_true, y_hat)) # RMSE

4.908148431451747

In [30]:
r2_score(y_true, y_hat), mean_absolute_error(y_true, y_hat)

(0.7279884238196066, 3.5397184331072786)